debug: true
app:
  jwtSecret: ${JWT_SECRET}
  version: 1.3.0

org:
  springframework:
    web:
      filter:
        CommonsRequestLoggingFilter: DEBUG

server:
  port: ${SERVER_PORT}
  ssl:
    key-alias: ${KEY_ALIAS}
    key-store-password: ${KEY_STORE_PASSWORD}
    key-store-type: PKCS12
    key-store: classpath:tanafaso.p12
    enabled: true


spring:
  data.mongodb:
    auto-index-creation: false
    uri: mongodb://${DATABASE_USER}:${DATABASE_PASSWORD}@localhost:27017/${DATABASE_NAME}
  http:
    log-request-details: true
  security.oauth2.client.registration.facebook:
    clientId: ${FACEBOOK_CLIENT_ID}
    clientSecret: ${FACEBOOK_CLIENT_SECRET}
    scope:
      - email
      - public_profile
  security.oauth2.client.registration.google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    scope:
      - email
      - profile
  resources.add-mappings: false
  mvc.throw-exception-if-no-handler-found: true

files:
  azkar: azkar.csv
  categories: categories.csv
