debug: true
app:
  jwtSecret: ${JWT_SECRET}
  version: 1.4.0

org:
  springframework:
    web:
      filter:
        CommonsRequestLoggingFilter: DEBUG

server:
  port: ${SERVER_PORT}
  ssl:
    enabled: false


spring:
  main:
    lazy-initialization: true
  data.mongodb:
    auto-index-creation: false
    uri: mongodb://${DATABASE_USER}:${DATABASE_PASSWORD}@localhost:27017/${DATABASE_NAME}
    name: ${DATABASE_NAME}
  http:
    log-request-details: true
  resources.add-mappings: false
  mvc.throw-exception-if-no-handler-found: true

files:
  azkar: azkar.csv
  categories: categories.csv
