app:
  jwtSecret: ${JWT_SECRET}

logging.level.org.springframework:
  web: DEBUG

server:
  port: ${SERVER_PORT}

spring:
  data.mongodb:
    auto-index-creation: false
    uri: mongodb://${DATABASE_USER}:${DATABASE_PASSWORD}@localhost:27017/${DATABASE_NAME}
  http:
    log-request-details: true
  security.oauth2.client.registration.facebook:
    clientId: ${FACEBOOK_CLIENT_ID}
    clientSecret: ${FACEBOOK_CLIENT_SECRET}
    scope:
      - email
      - public_profile
  security.oauth2.client.registration.google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    scope:
      - email
      - profile
