debug: true
app:
  jwtSecret: ${JWT_SECRET}
  version: 1.10.0

org:
  springframework:
    web:
      filter:
        CommonsRequestLoggingFilter: DEBUG

server:
  port: ${SERVER_PORT}
  ssl:
    key-alias: ${KEY_ALIAS}
    key-store-password: ${KEY_STORE_PASSWORD}
    key-store-type: PKCS12
    key-store: classpath:tanafaso.p12
    enabled: false

spring:
  main:
    lazy-initialization: true
  data.mongodb:
    auto-index-creation: false
    uri: ${DATABASE_URI}
    name: ${DATABASE_NAME}
    database: ${DATABASE_NAME}
  http:
    log-request-details: true
  resources.add-mappings: false
  mvc.throw-exception-if-no-handler-found: true

files:
  azkar: azkar.csv
  categories: categories.csv
  tafseer: tafseer.txt
  quran-metadata: quran_metadata.csv
  apple_auth_private_key: sign_in_with_apple_auth_key
