name: Build, Test & Package

on:
  push:
      branches:
        - master
  pull_request:
      branches:
        - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run Docker Compose
        run: docker compose -f docker-compose-test.yml up
